// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnjqwbohduhtupxxuvsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuanF3Ym9oZHVodHVweHh1dnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjM4MTksImV4cCI6MjA3MjEzOTgxOX0.CFfdq1ZUeuAqCuzwYTVuQi9NrknJ7j0XbMWbZ-PCUH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});